// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjdiQQmI4LngOHk2ieVSGelUfcP_9UiQ',
    appId: '1:1047522003610:web:d5e85d92eafbbe426cad23',
    messagingSenderId: '1047522003610',
    projectId: 'manchi-app',
    authDomain: 'manchi-app.firebaseapp.com',
    storageBucket: 'manchi-app.firebasestorage.app',
    measurementId: 'G-X39FFH97QC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5zbvfbM1tBnrz2KFMPFIUaTOCiufwrgg',
    appId: '1:1047522003610:android:4ded406112c3bee06cad23',
    messagingSenderId: '1047522003610',
    projectId: 'manchi-app',
    storageBucket: 'manchi-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrb7qjOw2VzXUsGszgNqHNhORHiGIXfP0',
    appId: '1:1047522003610:ios:d0b85007dcada8416cad23',
    messagingSenderId: '1047522003610',
    projectId: 'manchi-app',
    storageBucket: 'manchi-app.firebasestorage.app',
    iosBundleId: 'com.webcheezy.manchi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrb7qjOw2VzXUsGszgNqHNhORHiGIXfP0',
    appId: '1:1047522003610:ios:d0b85007dcada8416cad23',
    messagingSenderId: '1047522003610',
    projectId: 'manchi-app',
    storageBucket: 'manchi-app.firebasestorage.app',
    iosBundleId: 'com.webcheezy.manchi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqjdiQQmI4LngOHk2ieVSGelUfcP_9UiQ',
    appId: '1:1047522003610:web:c2d3814163a9a5aa6cad23',
    messagingSenderId: '1047522003610',
    projectId: 'manchi-app',
    authDomain: 'manchi-app.firebaseapp.com',
    storageBucket: 'manchi-app.firebasestorage.app',
    measurementId: 'G-G641CCCTRQ',
  );
}
